server:
  port: 8280

logging:
  level:
    com.intellibucket: debug
    org.springframework.web: error
    org.hibernate: error
    org.apache.kafka: error

company-service:
  url: http://localhost:2121/

order-service:
  payment-response-topic-name: payment-response

  payment-refund-topic-name: payment-refund-request
  payment-refund-response-topic-name: payment-refund-response

  company-order-approve-request-topic-name: company-order-approve-request
  company-order-approve-response-topic-name: company-order-approve-response

  start-delivery-request-topic-name: start-delivery-request
  order-delivered-response-topic-name: order-delivered-response

  order-completed-topic-name: order-completed
  outbox-scheduler-fixed-rate: 10000
  outbox-scheduler-initial-delay: 10000
  company-order-refund-request-topic-name: company-order-refund-request-topic

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:9114/postgres
    username: postgres
    password: admin

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  num-of-partitions: 1
  replication-factor: 1

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: none
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 1

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  order-service-consumer-group-id: order-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150


test:
  current:
    company:
      id: 01924d1f-a2f8-7825-9730-15ebaf6d4738
    customer:
      id: 01924d1f-a2f8-7bce-833e-d5ef9561d17a
    courier:
      id: 01924d1f-a2f8-7630-b7a5-b5c2130e5053

