services:
  postgres-order:
    container_name: postgres-order
    image: postgres:16
    ports:
      - "9114:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - 9114
    volumes:
      - './volumes/postgresql/data:/var/lib/postgresql/data'
volumes:
  order-volume: