#logging:
#  level:
#    root: error
#    com.intellibucket: error
spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    port: 587
    username: orucmollaev@gmail.com
    password: xbuw ttoz ewxt jwgp
#  datasource:
#    hikari:
#      connection-timeout: 30000
#    url: jdbc:postgres://localhost:9116/delivery
#    username: root
#    password: qwerty1212

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:9116/postgres
    username: postgres
    password: admin


issue:
  key: WmFxYXRhbGExOTkwMjAxODIwMTkyMDIyTWFoaXJBeWxpbjkwT3g5NjJIYXlhbGxlckFtZXJpa2FIYXlhdGxhcg==
security:
  jwt:
    expiration-time: 3600000


env:
  test:
    current:
      user:
        id: 0192720a-0ae9-714b-8d37-8f48051a5256