logging:
  level:
    #    root: info
    com.intellibucket: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: root
    password: qwerty1212
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  main:
    allow-circular-references: true
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/delivery
#    username: postgres
#    password: qwerty1212
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update # Use 'create' for fresh schema, 'update' for updating schema, 'validate' for checking schema validity
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true # To show SQL queries in logs
#    properties:
#      hibernate:
#        format_sql: true # To format SQL queries nicely in the logs

#        open-in-view: false

env:
  test:
    current:
      customer:
        id: 01925279-9713-732a-b558-e2785fe6c07f

      company:
        id: 01925279-af65-7f45-b68a-6a48cbada2ee


